(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "https://marmalade-repo.org/packages/")
(source "melpa" "https://melpa.org/packages/")

(depends-on "enh-ruby-mode")
(depends-on "cask")
(depends-on "magit")
(depends-on "smex")
(depends-on "popup")
(depends-on "auto-complete")
(depends-on "ruby-end")
(depends-on "full-ack")
(depends-on "markdown-mode")
(depends-on "multi-term")
(depends-on "ag")
(depends-on "gist")
(depends-on "grizzl")
(depends-on "projectile")
(depends-on "projectile-rails")
(depends-on "go-projectile")
(depends-on "helm-projectile")
(depends-on "github-browse-file")
(depends-on "yaml-mode")
(depends-on "haml-mode")
(depends-on "rspec-mode")
(depends-on "coffee-mode")
(depends-on "sass-mode")
(depends-on "flx-ido")
(depends-on "go-autocomplete")
(depends-on "protobuf-mode")
(depends-on "chruby")
(depends-on "slim-mode")
(depends-on "inf-ruby")
(depends-on "smart-mode-line")
(depends-on "dash-at-point")
(depends-on "web-mode")
(depends-on "elixir-mode")
(depends-on "ruby-tools")
(depends-on "go-mode")
(depends-on "gotest")
(depends-on "ivy")
(depends-on "vue-mode")
(depends-on "vue-html-mode")
(depends-on "rspec-mode")
(depends-on "rainbow-delimiters")
